export { fs } from '../infra/fs'
export { socket } from '../infra/socket'
export { StagingManager } from '../infra/staging/staging-manager'
export type { SocketMessage, SocketServer } from '../infra/socket'
export { GLOBAL_BOUNDARY_PATH, DAEMON_SOCK_PATH, DAEMON_PID_PATH, DAEMON_LOG_PATH, GLOBAL_PROOFS_PATH, COMMON_PROOFS_PATH } from '../infra/global'

export { executeProbe, executeProbeList, reduceToVerdict } from './probes/executor'
export type { Probe as ProbeFromExecutor, ProbeResult, ProbeContext, ProbeExecutor } from './probes/executor'

export type { TaskStatus, StepStatus, BlueprintStatus, ArtifactType, ProofType, ProjectStatus, ProbeType, Action } from './enums'
export { BOUNDARY_DIR, TASKS_DIR, CONFIG_FILE } from './constants'

export { BlueprintSchema, StageSchema, ProofSchema, ProbeSchema, parseBlueprint, safeParseBlueprint } from './schemas/blueprint.schema'
export type { Blueprint, Stage, Proof, Probe as ProbeSchemaType } from './schemas/blueprint.schema'

export { getTaskDirectory, ensureTaskDirectory, taskDirectoryExists, validateTaskId } from './lib/task-dir'
export type { TaskDirectory } from './lib/task-dir'
export type { Task } from './lib/types/task'
export type { Stage as StageType } from './lib/types/stage'
export type { ProofMetadata, ProofLayer, ProofCategory, ProofInput, ProofOutput, ProofResult, ProofExecutionContext, BuiltInProofDefinition, CustomProofConfig, ForbiddenProofType } from './lib/types/proof'
export type { Artifact } from './lib/types/artifact'
export type { Spec } from './lib/types/spec'
export type { Sample } from './lib/types/sample'
export type { TaskTraceState, StageState, TraceEvent, ProbeResult as ProbeResultType, TaskTraceYaml, StageTrace, TraceEventType } from './lib/types'

export { readTaskTraceFromContent, reduceTraceEvents, getTaskStatus, getNextPendingStage, getStageState, createProbeResult, createStageState, buildTraceEvent } from './lib/task-trace'
export { readBlueprint, parseBlueprintYaml } from './lib/blueprint-parser'
export type { ParsedBlueprint } from './lib/blueprint-parser'
export { getProjectBoundaryPath, getProjectConfigPath, getProjectProofsPath, getTasksPath, getTaskPath, getStepManifestPath, getProjectArsenalPath, getTaskTracePath } from './lib/project'
export { scanProjectProofs, scanGlobalProofs, getAllCustomProofs, findCustomProof, getGlobalProofsPath, getProjectProofsPath as getProjectProofsPathFn } from './lib/custom-proofs-scanner'
export { FORBIDDEN_PROOF_TYPES, isForbiddenProof, validateProofType, getForbiddenReason, filterForbiddenProofs, getForbiddenProofTypes } from './proof-blacklist'
export { validateProofInput, getProofSchema, serializeProofInput, deserializeProofInput, STANDARD_PROOF_SCHEMAS } from './proof-parameters'
export { validateDagTopology, topologicalSort } from './schemas/dag-validator'
export type { DagNode, DagValidationResult } from './schemas/dag-validator'
export { Action as ActionType, ProductionPolicy, SandboxPolicy, getExecutionPolicy } from './policy'
export type { ExecutionPolicy, ExecutionContext } from './policy'

export { process } from '../infra/process'
export type { ExecResult } from '../infra/process'