export { fs } from './infra/fs'
export { process } from './infra/process'
export { socket } from './infra/socket'
export { StagingManager } from './infra/staging/staging-manager'
export type { ExecResult } from './infra/process'
export type { SocketMessage, SocketServer } from './infra/socket'
export { GLOBAL_BOUNDARY_PATH, DAEMON_SOCK_PATH, DAEMON_PID_PATH, DAEMON_LOG_PATH, GLOBAL_PROOFS_PATH, COMMON_PROOFS_PATH } from './infra/global'

export { executeProbe, executeProbeList, reduceToVerdict } from './probes/executor'
export type { Probe, ProbeResult, ProbeContext, ProbeExecutor } from './probes/executor'

export * from './enums'
export * from './constants'
export * from './schemas/blueprint.schema'
export * from './lib/types'

export { getTaskDirectory, ensureTaskDirectory, taskDirectoryExists, validateTaskId } from './lib/task-dir'
export type { TaskDirectory } from './lib/task-dir'
export { createTaskTrace, readTaskTrace, appendTaskStatus, appendStageStart, appendStageComplete, appendProbeResult, getTaskStatus, getNextPendingStage, getStageState, createProbeResult, createStageState } from './lib/task-trace'
export type { TaskTraceState, StageState, TraceEvent, ProbeResult as ProbeResultLib } from './lib/task-trace'
export { readBlueprint, parseBlueprintYaml } from './lib/blueprint-parser'
export type { ParsedBlueprint } from './lib/blueprint-parser'
export { getProjectBoundaryPath, getProjectConfigPath, getProjectProofsPath, getTasksPath, getTaskPath, getStepManifestPath, getProjectArsenalPath, getTaskTracePath } from './lib/project'
export { scanProjectProofs, scanGlobalProofs, getAllCustomProofs, findCustomProof, getGlobalProofsPath, getProjectProofsPath as getProjectProofsPathFn } from './lib/custom-proofs-scanner'
export type { CustomProofConfig } from './lib/types/proof'
export { FORBIDDEN_PROOF_TYPES, isForbiddenProof, validateProofType, getForbiddenReason, filterForbiddenProofs, getForbiddenProofTypes } from './proof-blacklist'
export type { ForbiddenProofType } from './lib/types/proof'
export { validateProofInput, getProofSchema, serializeProofInput, deserializeProofInput, STANDARD_PROOF_SCHEMAS } from './proof-parameters'
export type { ProofInput } from './lib/types/proof'
export { scanProjectProofs as scanProjectProofsFn, scanGlobalProofs as scanGlobalProofsFn, getAllCustomProofs as getAllCustomProofsFn, findCustomProof as findCustomProofFn } from './lib/proofs-project'
export { listBuiltInProofs, getBuiltInProofsByLayer, getAllBuiltInProofs, executeBuiltInProof, hasBuiltInProof, getBuiltInProof } from './built-in-proofs-registry'
export type { BuiltInProofDefinition, ProofOutput, ProofExecutionContext } from './lib/types/proof'
export { validateDagTopology, topologicalSort } from './schemas/dag-validator'
export type { DagNode, DagValidationResult } from './schemas/dag-validator'
export { Action, ProductionPolicy, SandboxPolicy, getExecutionPolicy } from './policy'
export type { ExecutionPolicy, ExecutionContext } from './policy'