// =============================================================================
// oxn-serializer.test.ts — v0.4 Phase 2 unit tests
//
// 覆盖 3 个序列化函数:
//   - serializeDomainToOxn → langium parse → 验证 AST 结构
//   - serializeBlueprintToOxn → langium parse
//   - serializeWorkToOxn → langium parse
//
// 关键不变量:
//   - 序列化输出必通过 langium parser (不报语法错误)
//   - round-trip: IR → .oxn → parse → 验证关键字段
// =============================================================================

import { describe, expect, test } from 'bun:test'
import { serializeDomainToOxn, serializeBlueprintToOxn, serializeWorkToOxn } from '../oxn-serializer'
import type { DomainIR } from '../transformers/domain'
import type { BlueprintIR } from '../transformers/blueprint'
import type { WorkIR } from '../transformers/work'
import { createOxnParser } from '../../../oxl'
import { URI } from 'langium'

/** 验证 .oxn 能被 langium 解析 (不抛错) */
async function assertParseable(oxnContent: string, desc: string): Promise<void> {
  // 每次创建新 parser (避免 singleton 状态污染 — 并发测试下必须)
  const parser = createOxnParser()
  const result = await parser.parse(oxnContent, URI.file('test.oxn'))
  if (result.parseErrors.length > 0) {
    throw new Error(`${desc}: ${result.parseErrors.length} parse errors: ${result.parseErrors[0]}`)
  }
}

// ========================================================================
// 构建最小 DomainIR fixture
// ========================================================================

function makeDomainIR(overrides: Partial<DomainIR> = {}): DomainIR {
  return {
    entity: 'domain',
    name: 'TestContext',
    version: '0.3.0',
    description: 'Test domain for serializer unit tests',
    terms: [
      { id: 'term-foo', name: 'Foo', desc: 'A foo thing' },
      { id: 'term-bar', name: 'Bar', desc: 'A bar thing' },
    ],
    bans: [{ id: 'ban-1', items: ['forbidden_word'], desc: 'no bad words' }],
    invariants: [{ id: 'inv-rule-1', value: 'Rule 1: Must be valid', desc: 'desc' }],
    stack: [{ id: 'stack-ts', name: 'TypeScript', fields: [{ key: 'version', value: '5.x' }] }],
    _counters: { termIdx: 2, banIdx: 1, invIdx: 1, stackIdx: 1 },
    ...overrides,
  }
}

function makeBlueprintIR(overrides: Partial<BlueprintIR> = {}): BlueprintIR {
  return {
    entity: 'blueprint',
    name: 'dev-workflow',
    version: '1',
    description: 'Dev pipeline',
    props: [],
    slots: [
      { name: 'build', deps: [], observe: [] },
      { name: 'develop', deps: ['build'], observe: ['lint'] },
    ],
    _counters: { propIdx: 0, slotIdx: 2 },
    ...overrides,
  }
}

function makeWorkIR(overrides: Partial<WorkIR> = {}): WorkIR {
  return {
    entity: 'work',
    name: 'my-work',
    version: '0.3.0',
    context: { goal: 'Test work', maxIterations: 3, constraints: [] },
    refs: [],
    tasks: [
      {
        name: 'step-1',
        domain: null,
        blueprint: 'dev-workflow',
        parts: [{ name: 'build', skillContext: 'build stuff', probes: [] }],
      },
    ],
    proofs: [],
    _counters: { refIdx: 0, taskIdx: 1 },
    ...overrides,
  }
}

// ========================================================================
// Domain serializer tests
// ========================================================================

describe('serializeDomainToOxn', () => {
  test('output is parseable by langium', async () => {
    const ir = makeDomainIR()
    const oxn = serializeDomainToOxn(ir)
    await assertParseable(oxn, 'domain minimal')
  })

  test('contains all term names', () => {
    const oxn = serializeDomainToOxn(makeDomainIR())
    expect(oxn).toContain('"Foo":')
    expect(oxn).toContain('"Bar":')
  })

  test('contains ban items', () => {
    const oxn = serializeDomainToOxn(makeDomainIR())
    expect(oxn).toContain('forbidden_word')
  })

  test('contains invariant values', () => {
    const oxn = serializeDomainToOxn(makeDomainIR())
    expect(oxn).toContain('Rule 1: Must be valid')
  })

  test('stack info emitted as comments', () => {
    const oxn = serializeDomainToOxn(makeDomainIR())
    expect(oxn).toContain('// ═══ Stack')
    expect(oxn).toContain('// TypeScript')
  })

  test('header comment includes entity name', () => {
    const oxn = serializeDomainToOxn(makeDomainIR(), '2026-01-01T00:00:00.000Z')
    expect(oxn).toContain('// Domain: TestContext — Generated by oxn sync-md')
    expect(oxn).toContain('synced at: 2026-01-01T00:00:00.000Z')
  })

  test('empty terms/empty bans produce minimal valid document', async () => {
    const ir = makeDomainIR({ terms: [], bans: [], invariants: [], stack: [] })
    const oxn = serializeDomainToOxn(ir)
    await assertParseable(oxn, 'empty domain')
  })
})

// ========================================================================
// Blueprint serializer tests
// ========================================================================

describe('serializeBlueprintToOxn', () => {
  test('output is parseable by langium', async () => {
    const ir = makeBlueprintIR()
    const oxn = serializeBlueprintToOxn(ir)
    await assertParseable(oxn, 'blueprint minimal')
  })

  test('contains version', () => {
    const oxn = serializeBlueprintToOxn(makeBlueprintIR())
    expect(oxn).toContain('version = 1')
  })

  test('contains slot names', () => {
    const oxn = serializeBlueprintToOxn(makeBlueprintIR())
    expect(oxn).toContain('slot "build"')
    expect(oxn).toContain('slot "develop"')
  })

  test('slot deps preserved', () => {
    const oxn = serializeBlueprintToOxn(makeBlueprintIR())
    expect(oxn).toContain('"build"')
    expect(oxn).toContain('deps = [')
  })
})

// ========================================================================
// Work serializer tests
// ========================================================================

describe('serializeWorkToOxn', () => {
  test('output is parseable by langium', async () => {
    const ir = makeWorkIR()
    const oxn = serializeWorkToOxn(ir)
    await assertParseable(oxn, 'work minimal')
  })

  test('contains goal', () => {
    const oxn = serializeWorkToOxn(makeWorkIR())
    expect(oxn).toContain('goal = "Test work"')
  })

  test('contains task names', () => {
    const oxn = serializeWorkToOxn(makeWorkIR())
    expect(oxn).toContain('task "step-1"')
  })

  test('contains part with skill_context', () => {
    const oxn = serializeWorkToOxn(makeWorkIR())
    expect(oxn).toContain('part "build"')
    expect(oxn).toContain('build stuff')
  })

  test('constraints single-line format', () => {
    const ir = makeWorkIR()
    ir.context.constraints = ['C1', 'C2']
    const oxn = serializeWorkToOxn(ir)
    expect(oxn).toContain('constraints = ["C1", "C2"];')
  })
})
