import { defineCommand } from 'citty'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'
import { URI } from 'langium'
import { BOUNDARY_DIR } from '../kernel/constants'
import {
  createOxnParser,
  isBlueprintDeclaration,
  isPartDeclaration,
  isWorkDeclaration,
  type BlueprintDeclaration,
  type OXNDocument,
  type PartDeclaration,
  type PartSkill,
  type WorkContext,
  type WorkDeclaration,
} from '../oxn-dsl'
import {
  appendTrace,
  createInitialState,
  ensureWorkDir,
  getFrozenPath,
  loadState,
  saveState,
  stateExists,
  type PartExecution,
  type PartSkillSnapshot,
  type PartSpec,
  type SkillContextSnapshot,
  type WorkState,
} from '../work'
import { output, outputError, getFormatFromArgs } from './output'

// =============================================================================
// Unified `oxn leader` command (Phase 2.3).
//
// Primary subcommands (mvp-style, full state machine):
//   new         — generate work.oxn from a blueprint
//   run         — start the state machine
//   submit      — advance one part (optionally run aligned probes)
//   status      — read current state
//
// Reference-style aliases (kept for backward compatibility with
// users who already scripted around the old `start|next|list`):
//   start       — alias for `new`
//   next        — alias for `submit --run-probes`
//   list        — list builtin ldr-*.oxn templates (reference semantics)
// =============================================================================

const WORKS_DIR = 'works'
const BUILTIN_TEMPLATES_DIR = join(__dirname, '..', 'leader', 'works')

function getProjectRoot(): string {
  return process.cwd()
}

function getWorkDir(workName: string): string {
  return join(getProjectRoot(), BOUNDARY_DIR, WORKS_DIR, workName)
}

function ensureDirectory(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
}

type SkillContextJson = {
  overallGoal: string
  constraints: string[]
  currentFocus: string
  loopPolicy: { currentIteration: number; maxIterations: number }
}

type PartSkillJson = {
  lifecycle: string
  objective: string
  acceptance: string[]
  guidance?: string
}

type SkillReport = {
  workName: string
  overallStatus: 'pending' | 'running' | 'passed' | 'failed' | 'error'
  skillContext: SkillContextJson
  parts: Array<{
    partName: string
    align: string
    ref?: string
    lifecycle: string
    status: 'pending' | 'running' | 'passed' | 'failed'
    stepSkillContext: PartSkillJson
    probeResults: Array<{
      probe: string
      passed: boolean
      output?: unknown
      errorMessage?: string
      durationMs?: number
    }>
  }>
  loopMeta: { isLooping: boolean; iteration: number; maxIterations: number }
  frozen: string | null
}

function readTextFile(filePath: string): string {
  return readFileSync(resolve(filePath), 'utf-8')
}

async function parseOxnFile(
  filePath: string,
): Promise<{ doc: OXNDocument; work: WorkDeclaration | null; parts: PartDeclaration[] }> {
  const parser = createOxnParser()
  const content = readTextFile(filePath)
  const result = await parser.parse(content, URI.file(resolve(filePath)))
  if (result.parseErrors.length > 0 || result.lexerErrors.length > 0) {
    throw new Error(`DSL parse failed: ${[...result.parseErrors, ...result.lexerErrors].join('; ')}`)
  }
  const doc = result.ast as OXNDocument
  const work = doc.entities.find(isWorkDeclaration) ?? null
  const parts = doc.entities.filter(isPartDeclaration)
  return { doc, work, parts }
}

function snapshotSkill(skill: import('../oxn-dsl').PartSkill | undefined): PartSkillSnapshot {
  if (!skill) {
    return { lifecycle: 'code', objective: '', acceptance: [] }
  }
  return {
    lifecycle: skill.lifecycle ?? 'code',
    objective: skill.objective ?? '',
    acceptance: skill.acceptance ?? [],
    ...(skill.guidance !== undefined ? { guidance: skill.guidance } : {}),
  }
}

function snapshotContext(ctx: WorkContext | undefined, maxIters: number): SkillContextSnapshot {
  return {
    overallGoal: ctx?.goal ?? '',
    constraints: ctx?.constraints ?? [],
    maxIterations: ctx?.loopPolicy?.maxIterations ?? maxIters,
  }
}

function parsePartName(raw: string): string {
  return raw.replace(/^"|"$/g, '')
}

function defaultLifecycleForSlot(slotName: string): string {
  const name = slotName.toLowerCase()
  if (name === 'test' || name === 'verify' || name === 'validate' || name === 'check') return 'test'
  if (name === 'fix' || name === 'develop' || name === 'implement' || name === 'build' || name === 'refactor') {
    return 'fix'
  }
  return 'code'
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1)
}

function renderWorkSkeleton(
  workName: string,
  blueprintName: string,
  slots: Array<{ name: string; align: string }>,
): string {
  const header = [
    `// Generated by \`oxn leader new\` from blueprint "${blueprintName}"`,
    `// Edit goal/constraints and each part's skill, then run:`,
    `//   oxn leader run --work-file work.oxn`,
    '',
  ].join('\n')
  const slotBindings = slots.map((s) => `  part "${s.name}" align "${s.align}" { }`).join('\n')
  const partDefs = slots
    .map((s) => {
      const lifecycle = defaultLifecycleForSlot(s.name)
      return `part "${s.name}" align "${s.align}" {
  skill {
    lifecycle = "${lifecycle}";
    objective = "TODO: 描述 ${s.name} 阶段要做什么";
    acceptance = [
      "TODO: 列出可验收的产出"
    ];
    guidance = "TODO: 提示给 AI 的额外指引";
  }
}`
    })
    .join('\n\n')
  return `${header}work "${workName}" ref "@oxn/blueprints/${blueprintName}" {
  context {
    goal = "TODO: 描述这个 work 要达成什么";
    constraints = [
      "TODO: 列出硬约束"
    ];
    loop_policy {
      max_iterations = 3;
    }
  }
${slotBindings}
}

${partDefs}
`
}

function partStatus(partName: string, state: WorkState): 'pending' | 'running' | 'passed' | 'failed' {
  if (state.completedParts.includes(partName)) return 'passed'
  if (state.currentPart === partName) return 'running'
  return 'pending'
}

function makeContextJson(
  ctx: SkillContextSnapshot | undefined,
  currentFocus: string,
  state: WorkState,
): SkillContextJson {
  return {
    overallGoal: ctx?.overallGoal ?? '',
    constraints: ctx?.constraints ?? [],
    currentFocus,
    loopPolicy: {
      currentIteration: state.loopMeta.currentIteration,
      maxIterations: state.loopMeta.maxIterations,
    },
  }
}

function makeReport(state: WorkState): SkillReport {
  const partSpecs = state.partSpecs ?? []
  const executions = state.partExecutions ?? []
  const execByName = new Map<string, PartExecution>()
  for (const ex of executions) execByName.set(ex.partName, ex)

  return {
    workName: state.workName,
    overallStatus: state.status,
    skillContext: makeContextJson(state.skillContext, state.currentPart ?? '', state),
    parts: partSpecs.map((p) => {
      const exec = execByName.get(p.partName)
      return {
        partName: p.partName,
        align: p.align,
        ...(p.ref !== undefined ? { ref: p.ref } : {}),
        lifecycle: p.skill.lifecycle,
        status: partStatus(p.partName, state),
        stepSkillContext: {
          lifecycle: p.skill.lifecycle,
          objective: p.skill.objective,
          acceptance: p.skill.acceptance,
          ...(p.skill.guidance !== undefined ? { guidance: p.skill.guidance } : {}),
        },
        probeResults: (exec?.probes ?? []).map((pr) => ({
          probe: pr.probeName,
          passed: pr.passed,
          ...(pr.output !== undefined ? { output: pr.output } : {}),
          ...(pr.errorMessage !== undefined ? { errorMessage: pr.errorMessage } : {}),
          ...(pr.durationMs !== undefined ? { durationMs: pr.durationMs } : {}),
        })),
      }
    }),
    loopMeta: {
      isLooping: state.loopMeta.currentIteration > 0,
      iteration: state.loopMeta.currentIteration,
      maxIterations: state.loopMeta.maxIterations,
    },
    frozen: state.frozenPath,
  }
}

function errorJson(
  code: string,
  message: string,
  suggestion?: string,
): { ok: false; error: { code: string; message: string; suggestion?: string } } {
  return {
    ok: false,
    error: suggestion ? { code, message, suggestion } : { code, message },
  }
}

async function buildPartSpecs(work: WorkDeclaration, inlineParts: PartDeclaration[]): Promise<PartSpec[]> {
  const inlineByName = new Map<string, PartDeclaration>()
  for (const p of inlineParts) inlineByName.set(parsePartName(p.name), p)

  const specs: PartSpec[] = []
  for (const slot of work.slotBindings) {
    const partName = parsePartName(slot.name)
    let ref: string | undefined = slot.ref
    let skill: PartSkill | undefined = slot.skill
    let align = slot.align

    const inline = inlineByName.get(partName)
    if (inline) {
      if (inline.skill) skill = inline.skill as PartSkill
      if (inline.align) align = inline.align
      if (inline.ref !== undefined) ref = inline.ref
    }

    specs.push({
      partName,
      align,
      ...(ref !== undefined ? { ref } : {}),
      skill: snapshotSkill(skill),
    })
  }

  if (specs.length === 0 && inlineParts.length > 0) {
    return inlineParts.map((p) => ({
      partName: parsePartName(p.name),
      align: p.align ?? '',
      ...(p.ref !== undefined ? { ref: p.ref } : {}),
      skill: snapshotSkill(p.skill),
    }))
  }

  return specs
}

async function runProbesForPart(
  _projectRoot: string,
  partSpec: PartSpec | undefined,
): Promise<Array<{ probe: string; passed: boolean; output?: unknown; errorMessage?: string; durationMs?: number }>> {
  // Probe execution is only available when the part carries a `ref` to a
  // builtin part (which holds the `observe` / `execution` list). For now
  // we run a no-op probe that confirms the part is reachable; downstream
  // refactors can plug in part-level probe registries.
  if (!partSpec?.ref) return []
  return [
    {
      probe: 'part-reachable',
      passed: true,
      output: { ref: partSpec.ref },
    },
  ]
}

// ---------------------------------------------------------------------------
// Subcommand: new
// ---------------------------------------------------------------------------
const newSubcommand = defineCommand({
  meta: {
    name: 'new',
    description: '从 Blueprint 生成 work 骨架文件 (work.oxn，part 实体已内联)，不启动状态机',
  },
  args: {
    'blueprint-file': {
      type: 'string',
      description: 'blueprint.oxn 文件路径 (默认: .openxenon/blueprints/<name>.oxn)',
    },
    name: { type: 'string', required: true, description: '新 work 的名称' },
    'output-dir': {
      type: 'string',
      description: '输出目录 (默认: .openxenon/works/<name>/)',
    },
    force: { type: 'boolean', description: '覆盖已存在的文件' },
    json: { type: 'boolean', description: 'JSON 格式输出' },
    yaml: { type: 'boolean', description: 'YAML 格式输出' },
  },
  async run(ctx) {
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    const customBlueprint = ctx.args['blueprint-file'] as string | undefined
    const workName = ctx.args.name as string
    const customOutputDir = ctx.args['output-dir'] as string | undefined
    const force = ctx.args['force'] === true
    const projectRoot = getProjectRoot()
    try {
      const defaultCandidates = [
        resolve(projectRoot, '.openxenon', 'blueprints', `${workName}.oxn`),
        resolve(projectRoot, '.openxenon', 'blueprints', workName, 'blueprint.oxn'),
      ]
      const blueprintPath = customBlueprint ? resolve(customBlueprint) : null
      let absBlueprint: string | null = blueprintPath
      if (!absBlueprint || !existsSync(absBlueprint)) {
        if (customBlueprint) {
          return outputError(
            { code: 'OXN_FILE_NOT_FOUND', message: `blueprint file not found: ${customBlueprint}` },
            format,
          )
        }
        const found = defaultCandidates.find((p) => existsSync(p))
        if (!found) {
          return outputError(
            {
              code: 'OXN_FILE_NOT_FOUND',
              message: `blueprint file not found: tried ${defaultCandidates.join(', ')}`,
              suggestion: 'pass --blueprint-file to point at an existing blueprint',
            },
            format,
          )
        }
        absBlueprint = found
      }
      const { doc } = await parseOxnFile(absBlueprint)
      const blueprint = doc.entities.find(isBlueprintDeclaration) as BlueprintDeclaration | undefined
      if (!blueprint) {
        return outputError(
          { code: 'OXN_NO_BLUEPRINT', message: `No Blueprint declaration found in ${absBlueprint}` },
          format,
        )
      }
      if (!blueprint.name) {
        return outputError({ code: 'OXN_INVALID_BLUEPRINT', message: 'Blueprint has no name' }, format)
      }
      if (blueprint.partSlots.length === 0) {
        return outputError(
          {
            code: 'OXN_INVALID_BLUEPRINT',
            message: `Blueprint "${blueprint.name}" has no part slots`,
          },
          format,
        )
      }
      const blueprintName = parsePartName(blueprint.name)
      const slots = blueprint.partSlots.map((s) => ({
        name: parsePartName(s.name),
        align: capitalize(parsePartName(s.name)),
      }))
      const outputDir = customOutputDir
        ? resolve(customOutputDir)
        : resolve(projectRoot, '.openxenon', 'works', workName)
      if (!force && existsSync(outputDir)) {
        return outputError(
          {
            code: 'OXN_OUTPUT_DIR_EXISTS',
            message: `output directory already exists: ${outputDir}`,
            suggestion: 'use --force to overwrite, or --output-dir to pick a new location',
          },
          format,
        )
      }
      mkdirSync(outputDir, { recursive: true })
      const workFile = resolve(outputDir, 'work.oxn')
      if (!force && existsSync(workFile)) {
        return outputError(
          {
            code: 'OXN_OUTPUT_FILE_EXISTS',
            message: `work.oxn already exists in ${outputDir}`,
            suggestion: 'use --force to overwrite',
          },
          format,
        )
      }
      const workContent = renderWorkSkeleton(workName, blueprintName, slots)
      writeFileSync(workFile, workContent, 'utf-8')
      output(
        {
          ok: true,
          data: {
            workName,
            outputDir,
            blueprintPath: absBlueprint,
            blueprint: {
              name: blueprintName,
              version: blueprint.version ?? 1,
              slotCount: slots.length,
              slots: slots.map((s) => s.name),
            },
            files: { work: workFile },
            nextStep: `Edit the file, then run: oxn leader run --work-file ${workFile} --json`,
          },
        },
        format,
      )
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      output(errorJson('OXN_DSL_PARSE_FAILED', message), format)
    }
  },
})

// ---------------------------------------------------------------------------
// Subcommand: run
// ---------------------------------------------------------------------------
const runSubcommand = defineCommand({
  meta: { name: 'run', description: '启动 work 状态机，输出 skillContext JSON' },
  args: {
    'work-file': { type: 'string', required: true, description: '.oxn 文件路径' },
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  async run(ctx) {
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    const filePath = ctx.args['work-file'] as string
    try {
      const { work, parts: inlineParts } = await parseOxnFile(filePath)
      if (!work) {
        return output(errorJson('OXN_NO_WORK', 'No Work declaration found in .oxn file'), format)
      }
      const projectRoot = getProjectRoot()
      const workName = parsePartName(work.name) || 'unnamed'
      if (stateExists(projectRoot, workName)) {
        return output(
          errorJson('OXN_WORK_ALREADY_EXISTS', `work "${workName}" already exists`, 'use oxn leader status to view'),
          format,
        )
      }
      ensureWorkDir(projectRoot, workName)
      const partSpecs = await buildPartSpecs(work, inlineParts)
      const partNames = partSpecs.map((p) => p.partName)
      const maxIters = work.context?.loopPolicy?.maxIterations ?? 3
      const state = createInitialState(workName, partNames, maxIters)
      state.skillContext = snapshotContext(work.context, maxIters)
      state.partSpecs = partSpecs
      saveState(projectRoot, workName, state)
      appendTrace(projectRoot, workName, {
        event: 'work-started',
        workName,
        blueprint: work.ref,
        parts: partSpecs.map((p) => p.partName),
        at: new Date().toISOString(),
      })
      output({ ok: true, data: makeReport(state) }, format)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      output(errorJson('OXN_DSL_PARSE_FAILED', message), format)
    }
  },
})

// ---------------------------------------------------------------------------
// Subcommand: submit
// ---------------------------------------------------------------------------
const submitSubcommand = defineCommand({
  meta: {
    name: 'submit',
    description: '提交证据，调度 Probe（如指定 --run-probes），更新状态机',
  },
  args: {
    'work-name': { type: 'string', required: true, description: 'Work 名称' },
    '--evidence': { type: 'string', description: 'AI 提交的证据 JSON' },
    '--run-probes': { type: 'boolean', description: '执行对齐到当前 part 的探针（reference 行为）' },
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  async run(ctx) {
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    const workName = ctx.args['work-name'] as string
    const runProbes = ctx.args['run-probes'] === true
    const projectRoot = getProjectRoot()
    try {
      const state = loadState(projectRoot, workName)
      if (!state) {
        return output(errorJson('OXN_WORK_NOT_FOUND', `work "${workName}" not found`), format)
      }
      const probeResults: Array<{
        probe: string
        passed: boolean
        output?: unknown
        errorMessage?: string
        durationMs?: number
      }> = []
      if (state.currentPart) {
        if (!state.completedParts.includes(state.currentPart)) {
          state.completedParts.push(state.currentPart)
        }
        probeResults.push({ probe: 'state-machine', passed: true, output: { advanced: true } })
      }

      // Optionally run aligned probes for the just-completed part
      if (runProbes && state.currentPart) {
        const partSpec = state.partSpecs?.find((p) => p.partName === state.currentPart)
        const startedAt = new Date()
        const probeOuts = await runProbesForPart(projectRoot, partSpec)
        for (const p of probeOuts) {
          probeResults.push({ ...p, durationMs: Date.now() - startedAt.getTime() })
        }
        // Persist into partExecutions so future status/submit reports it
        if (!state.partExecutions) state.partExecutions = []
        const exec = state.partExecutions.find((e) => e.partName === state.currentPart)
        if (exec) {
          for (const p of probeOuts) {
            exec.probes.push({
              probeName: p.probe,
              passed: p.passed,
              output: p.output,
              durationMs: p.durationMs,
              executedAt: new Date().toISOString(),
            })
          }
          exec.completedAt = new Date().toISOString()
          exec.status = 'passed'
        }
        appendTrace(projectRoot, workName, {
          event: 'probe-result',
          partName: state.currentPart,
          probes: probeOuts,
          at: new Date().toISOString(),
        })
      }

      state.loopMeta.currentIteration += 1
      const allPartNames = (state.partSpecs ?? []).map((p) => p.partName)
      const nextIdx = state.completedParts.length
      if (allPartNames.length > 0 && nextIdx >= allPartNames.length) {
        state.status = 'passed'
        state.currentPart = null
        state.frozenPath = getFrozenPath(projectRoot, workName)
        const frozen = {
          workName,
          generatedAt: new Date().toISOString(),
          probes: probeResults,
          trace: state.completedParts,
        }
        writeFileSync(state.frozenPath, JSON.stringify(frozen, null, 2), 'utf-8')
      } else if (allPartNames.length > 0) {
        state.currentPart = allPartNames[nextIdx] ?? null
      } else {
        state.status = 'passed'
        state.currentPart = null
        state.frozenPath = getFrozenPath(projectRoot, workName)
        const frozen = {
          workName,
          generatedAt: new Date().toISOString(),
          probes: probeResults,
          trace: state.completedParts,
        }
        writeFileSync(state.frozenPath, JSON.stringify(frozen, null, 2), 'utf-8')
      }
      saveState(projectRoot, workName, state)
      appendTrace(projectRoot, workName, {
        event: 'submit',
        iteration: state.loopMeta.currentIteration,
        probeResults,
        at: new Date().toISOString(),
      })
      output({ ok: true, data: makeReport(state) }, format)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      output(errorJson('OXN_LEADER_NEXT_FAILED', message), format)
    }
  },
})

// ---------------------------------------------------------------------------
// Subcommand: status
// ---------------------------------------------------------------------------
const statusSubcommand = defineCommand({
  meta: { name: 'status', description: '查询 work 当前状态' },
  args: {
    'work-name': { type: 'string', required: true, description: 'Work 名称' },
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  run(ctx) {
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    const workName = ctx.args['work-name'] as string
    const projectRoot = getProjectRoot()
    try {
      const state = loadState(projectRoot, workName)
      if (!state) {
        return output(errorJson('OXN_WORK_NOT_FOUND', `work "${workName}" not found`), format)
      }
      output({ ok: true, data: makeReport(state) }, format)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      output(errorJson('OXN_STATUS_FAILED', message), format)
    }
  },
})

// ---------------------------------------------------------------------------
// Aliases (reference compatibility)
// ---------------------------------------------------------------------------
const startSubcommand = defineCommand({
  meta: { name: 'start', description: '[alias of `new`] 从内置 ldr-*.oxn 模板生成 work.oxn' },
  args: {
    'work-name': { type: 'string', required: true, description: 'Work 名称' },
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  run(ctx) {
    // Reference semantics: copy a ldr-<name>.oxn builtin template into
    // .openxenon/works/<name>/work.oxn, then call into the same
    // initialization path as `new` would for a user-provided blueprint.
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    const workName = ctx.args['work-name'] as string
    const templateName = workName.startsWith('ldr-') ? workName : `ldr-${workName}`
    const sourceFile = join(BUILTIN_TEMPLATES_DIR, `${templateName}.oxn`)
    if (!existsSync(sourceFile)) {
      return outputError(
        {
          code: 'OXN_LEADER_NOT_FOUND',
          message: `Leader 模板不存在: ${templateName}.oxn`,
          suggestion: '使用 oxn leader list 查看可用模板',
        },
        format,
      )
    }
    const workDir = getWorkDir(workName)
    ensureDirectory(workDir)
    const destFile = join(workDir, 'work.oxn')
    const content = readFileSync(sourceFile, 'utf-8')
    writeFileSync(destFile, content, 'utf-8')
    output(
      {
        ok: true,
        data: { workName, path: destFile },
        human: `Leader 工作空间已创建: ${workName}\n路径: ${destFile}\n使用 oxn leader run --work-file ${destFile}`,
      },
      format,
    )
  },
})

const nextSubcommand = defineCommand({
  meta: { name: 'next', description: '[alias of `submit --run-probes`] 推进并执行探针' },
  args: {
    'work-name': { type: 'string', required: true, description: 'Work 名称' },
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  async run(ctx) {
    // Re-implement `submit --run-probes` so we don't depend on the
    // submitSubcommand's runtime function (which is bound to a more
    // permissive args type). We just delegate to a fresh context with
    // run-probes pre-set (citty strips the leading dashes).
    const augmented = {
      ...ctx,
      args: {
        ...ctx.args,
        'run-probes': true,
      },
    }
    return (submitSubcommand.run as unknown as (c: typeof augmented) => Promise<void>)(augmented)
  },
})

const listSubcommand = defineCommand({
  meta: { name: 'list', description: '列出内置 ldr-*.oxn 模板' },
  args: {
    '--json': { type: 'boolean', description: 'JSON 格式输出' },
    '--yaml': { type: 'boolean', description: 'YAML 格式输出' },
  },
  run(ctx) {
    const format = getFormatFromArgs(ctx.args as Record<string, unknown>)
    if (!existsSync(BUILTIN_TEMPLATES_DIR)) {
      return output({ ok: true, data: { templates: [] } }, format)
    }
    const files = readdirSync(BUILTIN_TEMPLATES_DIR).filter((f) => f.endsWith('.oxn') && f.startsWith('ldr-'))
    const templates = files.map((f) => ({
      name: f.replace('ldr-', '').replace('.oxn', ''),
      file: f,
    }))
    output(
      {
        ok: true,
        data: { templates },
        human:
          templates.length > 0 ? `可用模板:\n${templates.map((t) => `  ${t.file}`).join('\n')}` : '暂无 Leader 模板',
      },
      format,
    )
  },
})

export default defineCommand({
  meta: {
    name: 'leader',
    description: 'Leader 模块 — AI Agent 编排器，驱动 Work 状态机',
  },
  subCommands: {
    new: newSubcommand,
    run: runSubcommand,
    submit: submitSubcommand,
    status: statusSubcommand,
    // Reference compatibility aliases
    start: startSubcommand,
    next: nextSubcommand,
    list: listSubcommand,
  },
  run() {
    // No-op: help text is provided by citty
  },
})
