/**
 * Intent module — create-work use case (v0.6 PR-5b续)
 *
 * 生成 work.oxn 工作区骨架模板（.oxn + .md 两种格式）
 */
import type { AssetFormat } from '@openxenon/engine/infra/paths'
import type { CreateWorkInput, CreateWorkResult } from './types'

function renderWorkSkeleton(
  workName: string,
  blueprintName: string,
  slots: Array<{ name: string; align: string }>,
  format: AssetFormat = 'oxn',
  domains?: string[],
): string {
  if (format === 'md') {
    const refs = domains?.length
      ? domains.map((d) => `### ${d}\n- kind: domain\n- ref: "@prj/domains/${d}"`).join('\n\n')
      : ''
    const partEntries = slots
      .map((s) => `### ${s.name}\n- blueprint: ${blueprintName}\n- part: ${s.name}\n  - skill_context: TODO`)
      .join('\n\n')
    return `---
entity: work
version: 0.3.0
name: ${workName}
---

# Work: ${workName}

## Context
### primary
- goal: TODO
- max_iterations: 3
- constraints:
  - TODO

## Refs
${refs || `### ${blueprintName}\n- kind: blueprint\n- ref: "@prj/blueprints/${blueprintName}"`}

## Tasks
${partEntries}
`
  }
  const domainEntries = domains?.length
    ? domains.map((d) => `  domain "${d}" ref "@prj/domains/${d}";`).join('\n')
    : ''
  const blueprintEntry = `  blueprint "${blueprintName}" ref "@prj/blueprints/${blueprintName}";`
  return `// Generated by \`oxn work create\` from blueprint "${blueprintName}"
work "${workName}" {
  context {
    goal = "TODO"
    constraints = ["TODO"]
    loop_policy { max_iterations = 3 }
  }
${domainEntries}
${blueprintEntry}

${slots.map((s) => `  task "${s.name}" {\n    blueprint "${blueprintName}"\n    deps = []\n    part "${s.name}" { skill_context = "TODO" }\n  }`).join('\n\n')}
}
`
}

export async function createWork(input: CreateWorkInput): Promise<CreateWorkResult> {
  const content = renderWorkSkeleton(
    input.workName,
    input.assetRefs?.find((r) => r.kind === 'blueprint')?.name ?? 'dev-workflow',
    [{ name: 'build', align: 'build' }, { name: 'test', align: 'test' }],
    'oxn',
    input.assetRefs?.filter((r) => r.kind === 'domain').map((r) => r.name),
  )
  return { workPath: '', content, createdAt: new Date().toISOString() }
}
