import type { AssetFormat } from '../infra/paths'

export function renderWorkSkeleton(
  workName: string,
  blueprintName: string,
  slots: Array<{ name: string; align: string }>,
  format: AssetFormat = 'oxn',
): string {
  if (format === 'md') {
    const partEntries = slots
      .map((s) => {
        return `### ${s.name}
- blueprint: ${blueprintName}
- part: slot-name
  - skill_context: TODO: 描述 ${s.name} 阶段要做什么`
      })
      .join('\n\n')
    return `---
entity: work
version: 0.3.0
name: ${workName}
---

# Work: ${workName}

## Context

### primary
- goal: TODO: 描述这个 work 要达成什么
- max_iterations: 3
- constraints:
  - TODO: 列出硬约束

## LoopPolicy

### primary
- max_iterations: 3

## Refs

### ${blueprintName}
- kind: blueprint
- ref: "@prj/blueprints/${blueprintName}"

## Tasks

${partEntries}
`
  }
  const header = [
    `// Generated by \`oxn work create\` from blueprint "${blueprintName}"`,
    `// Edit goal/constraints and each task's objective, then run:`,
    `//   oxn work run <name>`,
    '',
  ].join('\n')
  const partEntries = slots
    .map((s) => {
      return `  task "${s.name}" {
    blueprint "${blueprintName}"
    part "slot-name" {
      skill_context = "TODO: 描述 ${s.name} 阶段要做什么"
    }
  }`
    })
    .join('\n')
  return `${header}work "${workName}" {
  context {
    goal = "TODO: 描述这个 work 要达成什么";
    constraints = [
      "TODO: 列出硬约束"
    ];
    } loop_policy {
      max_iterations = 3;
    }

  blueprint "${blueprintName}" ref "@prj/blueprints/${blueprintName}";

${partEntries}
}
`
}
