import type { AssetFormat } from '../infra/paths'

/**
 * v0.6.4: renderWorkSkeleton 增强
 * v0.6.1-alpha.4 Phase B: 删 domainNames + stackNames（work ## Refs 只接受 blueprint）
 *
 * 老接口（保持向后兼容 — domainNames/stackNames 仍接受但被忽略）：
 *   renderWorkSkeleton(workName, blueprintName, slots, format)
 *
 * 新 options（work create CLI 通过 options 传入）：
 *   - goal?: string                  直接写入 Context.goal（不再是 TODO 占位）
 *   - blueprintNames?: string[]      work 级 blueprint refs；如不传则 blueprintName 作为默认 1 个
 *   - constraints?: string[]         写 Context.constraints（不再是 TODO 占位）
 *
 * 行为：
 *   - 无 options（老调用方）：与原行为完全一致 — 1 blueprint ref、goal= TODO
 *   - 有 options（新调用方）：多 ref + 真 goal + 真 constraints
 */
export interface RenderWorkSkeletonOptions {
  goal?: string
  /** @deprecated v0.6.1-alpha.4 Phase B: Work ## Refs 只接受 blueprint；Domain/Stack 引用走 Blueprint ## Refs */
  domainNames?: string[]
  blueprintNames?: string[]
  /** @deprecated v0.6.1-alpha.4 Phase B: Work ## Refs 只接受 blueprint；Stack 引用走 Blueprint ## Refs */
  stackNames?: string[]
  constraints?: string[]
}

export function renderWorkSkeleton(
  workName: string,
  blueprintName: string,
  slots: Array<{ name: string; align: string }>,
  format: AssetFormat = 'oxn',
  options?: RenderWorkSkeletonOptions,
): string {
  if (format === 'md') {
    const partEntries = slots
      .map((s) => {
        return `### ${s.name}
- blueprint: ${blueprintName}
- part: slot-name
  - skill_context: TODO: 描述 ${s.name} 阶段要做什么`
      })
      .join('\n\n')

    // Goal + constraints 段：有 options 用真值，否则占位
    const goalLine = options?.goal !== undefined ? options.goal : 'TODO: 描述这个 work 要达成什么'
    const constraintLines =
      options?.constraints !== undefined
        ? options.constraints.map((c) => `  - ${c}`).join('\n')
        : '  - TODO: 列出硬约束'

    // ## Refs 段：v0.6.1-alpha.4 Phase B — 只生成 blueprint ref（domain/stack 通过 Blueprint ## Refs 组合）
    // blueprintNames: work 引用 1..N 个 blueprint；如不传则 blueprintName 作为默认 1 个
    // domainNames/stackNames: 已 deprecated，忽略（不生成 ## Refs 条目）
    const blueprintRefs =
      options?.blueprintNames && options.blueprintNames.length > 0 ? options.blueprintNames : [blueprintName] // 默认行为：老调用方传 1 个 blueprint

    const refsEntries: string[] = []
    for (const b of blueprintRefs) {
      // v0.6.1-alpha.3: Phase 1 — Work 引用 workflow（不是 blueprint）
      refsEntries.push(
        `### ${b}
- kind: blueprint
- ref: "@prj/workflows/${b}"`,
      )
    }
    const refsBlock = refsEntries.length > 0 ? `## Refs\n\n${refsEntries.join('\n\n')}\n\n` : ''

    return `---
entity: work
version: 0.3.0
name: ${workName}
---

# Work: ${workName}

## Context

### primary
- goal: ${goalLine}
- max_iterations: 3
- constraints:
${constraintLines}

## LoopPolicy

### primary
- max_iterations: 3

${refsBlock}## Tasks

${partEntries}
`
  }

  // OXN 格式（非 canonical；保留用于 v0.6.x 兼容）
  // v0.6.4: MD 为主格式。OXN 不写 stack ref（grammar 没有 StackRefDecl），
  //         stack 信息存于 .md 镜像；OXN 镜像丢弃 stack（autoSync 时）。
  const header = [
    `// Generated by \`oxn work create\` from blueprint "${blueprintName}"`,
    `// Edit goal/constraints and each task's objective, then run:`,
    `//   oxn work run <name>`,
    '',
  ].join('\n')

  const goalLine = options?.goal !== undefined ? options.goal : 'TODO: 描述这个 work 要达成什么'
  const constraintsBlock =
    options?.constraints !== undefined && options.constraints.length > 0
      ? options.constraints.map((c) => `      "${c}"`).join(',\n')
      : `      "TODO: 列出硬约束"`

  const blueprintRefs =
    options?.blueprintNames && options.blueprintNames.length > 0 ? options.blueprintNames : [blueprintName]
  const domainRefs = options?.domainNames ?? []
  // stack refs intentionally dropped for OXN format (see comment above)

  const refsBlock = [
    // v0.6.1-alpha.3: Phase 1 — Work 引用 workflow（不是 blueprint）
    ...blueprintRefs.map((b) => `  blueprint "${b}" ref "@prj/workflows/${b}";`),
    ...domainRefs.map((d) => `  domain "${d}" ref "@prj/domains/${d}";`),
  ].join('\n')

  // OXN 格式下的 task 排版：保持单 blueprint 默认（新 options 不能直接定制 task blueprint，
  // 让用户创建后用 edit-task 覆盖）
  const partEntries = slots
    .map((s) => {
      return `  task "${s.name}" {
    blueprint "${blueprintName}"
    part "slot-name" {
      skill_context = "TODO: 描述 ${s.name} 阶段要做什么"
    }
  }`
    })
    .join('\n')

  return `${header}work "${workName}" {
  context {
    goal = "${goalLine}";
    constraints = [
${constraintsBlock}
    ];
  } loop_policy {
    max_iterations = 3;
  }

${refsBlock}

${partEntries}
}
`
}
