import './fs-exists'
import './fs-not-exists'
import './fs-content-match'
import './fs-parseable'
import './exec-exit-zero'
import './exec-stdout-match'
import './db-query-bool'
import './env-exists'
import './http-status'

export { fsExistsProof } from './fs-exists'
export { fsNotExistsProof } from './fs-not-exists'
export { fsContentMatchProof } from './fs-content-match'
export { fsParseableProof } from './fs-parseable'
export { execExitZeroProof } from './exec-exit-zero'
export { execStdoutMatchProof } from './exec-stdout-match'
export { dbQueryBoolProof } from './db-query-bool'
export { envExistsProof } from './env-exists'
export { httpStatusProof } from './http-status'
