/**
 * oxn-serializer.ts — v0.4 Phase 2 IR → .oxn 反向编译
 *
 * 把 md-pipeline extractXxxIR 的输出转为 .oxn 格式文本。
 * v0.7.0 后 .oxn 已废弃，此文件仅保留供 v0.6.x 向后兼容参考。
 * 端到端不变量：
 *   1. 输出 .oxn 语法合法（不报解析错误）
 *   2. round-trip: serialize(extract(md)) → oxn → parse → IR ≈ 原 IR
 *   3. 注释丢失可接受 (RFC §3.2 明确定义)
 *   4. 字段顺序稳定 (不依赖 IR 对象 key 枚举顺序)
 *
 * L0–L3: L1-OXL 层
 */

import type { DomainIR } from './transformers/domain'
import type { BlueprintIR } from './transformers/blueprint'
import type { WorkIR } from './transformers/work'

// ========================================================================
// 字符串工具函数
// ========================================================================

/** 转义 .oxn STRING (双引号 → \", 反斜杠 → \\, 换行 → \n) */
function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

/** 生成 header 注释 */
function genHeader(entity: string, ts: string): string[] {
  return [`// ${entity} — Generated by oxn sync-md v0.4 Phase 2`, `// synced at: ${ts}`, '']
}

/** indent helper */
function indent(n: number, line: string): string {
  return '  '.repeat(n) + line
}

// ========================================================================
// Domain 序列化 (DomainIR → .oxn)
// ========================================================================

export function serializeDomainToOxn(ir: DomainIR, ts?: string): string {
  const now = ts ?? new Date().toISOString()
  const lines: string[] = [...genHeader(`Domain: ${ir.name}`, now)]

  lines.push(`domain "${escapeString(ir.name)}" {`)

  // description (v0.4.1: 直接用 IR.description, 不再回退到第一项 term)
  if (ir.description) {
    lines.push(indent(1, `description = "${escapeString(ir.description)}"`))
    lines.push('')
  } else {
    // 兼容旧 IR (无 description 字段): 回退到第一项 term
    for (const term of ir.terms) {
      if (term.desc && !lines.some((l) => l.includes('description ='))) {
        lines.push(indent(1, `description = "${escapeString(term.desc)}"`))
        lines.push('')
        break
      }
    }
  }

  // term block (all terms in one block, RFC §3.2 格式)
  if (ir.terms.length > 0) {
    lines.push(indent(1, 'term {'))
    for (const t of ir.terms) {
      lines.push(indent(2, `"${escapeString(t.name)}": "${escapeString(t.desc)}"`))
    }
    lines.push(indent(1, '}'))
    lines.push('')
  }

  // ban block (flatten all ban items into one block)
  const allBanItems = ir.bans.flatMap((b) => b.items)
  if (allBanItems.length > 0) {
    const banLine = `ban { ${allBanItems.map((i) => `"${escapeString(i)}"`).join(', ')} }`
    lines.push(indent(1, banLine))
    lines.push('')
  }

  // invariant block (all invariants in one block)
  if (ir.invariants.length > 0) {
    lines.push(indent(1, 'invariant {'))
    for (const inv of ir.invariants) {
      lines.push(indent(2, `"${escapeString(inv.value)}"`))
    }
    lines.push(indent(1, '}'))
    lines.push('')
  }

  // Stack → comment block (grammar 无 stack 关键字，写注释做信息保留)
  if (ir.stack.length > 0) {
    lines.push(indent(1, '// ═══ Stack (from .md ## Stack) ═══'))
    for (const s of ir.stack) {
      lines.push(indent(1, `// ${s.name}`))
      for (const f of s.fields) {
        const v = Array.isArray(f.value) ? f.value.join(', ') : String(f.value)
        lines.push(indent(1, `//   ${f.key}: ${v}`))
      }
    }
    lines.push('')
  }

  lines.push('}')
  return `${lines.join('\n')}\n`
}

// ========================================================================
// Blueprint 序列化 (BlueprintIR → .oxn)
// ========================================================================

export function serializeBlueprintToOxn(ir: BlueprintIR, ts?: string): string {
  const now = ts ?? new Date().toISOString()
  const lines: string[] = [...genHeader(`Blueprint: ${ir.name}`, now)]

  lines.push(`blueprint "${escapeString(ir.name)}" {`)

  // version (仅当格式合法 — NUMBER grammar 接受 N / N.M, 不接受 N.M.K)
  if (ir.version && /^\d+(\.\d+)?$/.test(ir.version)) {
    lines.push(indent(1, `version = ${ir.version}`))
  }

  // description
  if (ir.description) {
    lines.push(indent(1, `description = "${escapeString(ir.description)}"`))
  }

  // 🆕 v0.7: use 段（引用三边界）
  if (ir.use) {
    for (const d of ir.use.domain) {
      lines.push(indent(1, `domain "${escapeString(d.name)}" ref "${escapeString(d.ref)}";`))
    }
    for (const w of ir.use.workflow) {
      lines.push(indent(1, `workflow "${escapeString(w.name)}" ref "${escapeString(w.ref)}";`))
    }
    for (const s of ir.use.stack) {
      lines.push(indent(1, `stack "${escapeString(s.name)}" ref "${escapeString(s.ref)}";`))
    }
  }
  if (ir.use.domain.length || ir.use.workflow.length || ir.use.stack.length) lines.push('')

  // 🆕 v0.7: boundary declarations（替代 slot declarations）
  for (const boundary of ir.boundaries) {
    lines.push(indent(1, `boundary "${escapeString(boundary.name)}" {`))
    if (boundary.refs.length > 0) {
      const refsStr = boundary.refs.map((r) => `${r.kind} "${escapeString(r.ref)}"`).join(', ')
      lines.push(indent(2, `refs = [${refsStr}]`))
    }
    if (boundary.observe.length > 0) {
      lines.push(indent(2, `observe = [${boundary.observe.map((o) => `"${escapeString(o)}"`).join(', ')}]`))
    }
    if (boundary.deps.length > 0) {
      lines.push(indent(2, `deps = [${boundary.deps.map((d) => `"${escapeString(d)}"`).join(', ')}]`))
    }
    lines.push(indent(1, '}'))
  }

  lines.push('}')
  return `${lines.join('\n')}\n`
}

// ========================================================================
// Work 序列化 (WorkIR → .oxn)
// ========================================================================

export function serializeWorkToOxn(ir: WorkIR, ts?: string): string {
  const now = ts ?? new Date().toISOString()
  const lines: string[] = [...genHeader(`Work: ${ir.name}`, now)]

  lines.push(`work "${escapeString(ir.name)}" {`)

  // context block (v0.4.1: loopPolicy 移出, 独立 H2)
  lines.push(indent(1, 'context {'))
  lines.push(indent(2, `goal = "${escapeString(ir.context.goal)}";`))
  const constraints = ir.context.constraints
  if (constraints.length > 0) {
    const constraintItems = constraints.map((c) => `"${escapeString(c)}"`).join(', ')
    lines.push(indent(2, `constraints = [${constraintItems}];`))
  }
  lines.push(indent(1, '}'))
  lines.push('')

  // loop_policy block (v0.4.1: 移出 WorkContext, 放 work-level)
  lines.push(indent(1, 'loop_policy {'))
  lines.push(indent(2, `max_iterations = ${ir.context.maxIterations};`))
  lines.push(indent(1, '}'))
  lines.push('')

  // work-level ref pool (domain / blueprint / stack)
  // v0.6.4: stack ref 在 MD 里有正式声明 (kind: stack)，但 OXL grammar 没有
  //         StackRefDecl → serializer 把 stack 写到注释里保留信息，避免 .oxn parse 失败。
  const stackRefsAsComment: string[] = []
  for (const ref of ir.refs) {
    if (ref.kind === 'stack') {
      stackRefsAsComment.push(`stack "${escapeString(ref.name)}" ref "${escapeString(ref.ref)}"`)
      continue
    }
    const refParts: string[] = []
    if (ref.alias) refParts.push(`as "${escapeString(ref.alias)}"`)
    refParts.push(`ref "${escapeString(ref.ref)}"`)
    lines.push(indent(1, `${ref.kind} "${escapeString(ref.name)}" ${refParts.join(' ')};`))
  }
  if (ir.refs.length > 0) lines.push('')

  // Stack refs → comment block (与 DomainIR.stack 同样处理)
  if (stackRefsAsComment.length > 0) {
    lines.push(indent(1, '// ═══ Stack refs (Work-level; OXN 无 StackRefDecl grammar，下沉到 .md) ═══'))
    for (const s of stackRefsAsComment) lines.push(indent(1, `// ${s}`))
    lines.push('')
  }

  // task declarations (每个 task 映射一个 task 块)
  for (const task of ir.tasks) {
    lines.push(indent(1, `task "${escapeString(task.name)}" {`))
    if (task.domain) {
      lines.push(indent(2, `domain "${escapeString(task.domain)}"`))
    }
    if (task.blueprint) {
      lines.push(indent(2, `blueprint "${escapeString(task.blueprint)}"`))
    }
    for (const part of task.parts) {
      lines.push(indent(2, `part "${escapeString(part.name)}" {`))
      if (part.skillContext) {
        lines.push(indent(3, `skill_context = "${escapeString(part.skillContext)}"`))
      }
      for (const probe of part.probes) {
        lines.push(indent(3, `probe "${escapeString(probe.name)}" {`))
        lines.push(indent(4, `ref "${escapeString(probe.name)}"`))
        if (probe.scheme) lines.push(indent(4, `scheme: "${escapeString(probe.scheme)}"`))
        if (probe.expect) lines.push(indent(4, `expect "${escapeString(probe.expect)}"`))
        lines.push(indent(3, '}'))
      }
      lines.push(indent(2, '}'))
    }
    lines.push(indent(1, '}'))
    lines.push('')
  }

  // proofs (v0.3 T11 grammar)
  if (ir.proofs.length > 0) {
    lines.push(indent(1, `proofs [${ir.proofs.map((p) => `"${escapeString(p)}"`).join(', ')}]`))
    lines.push('')
  }

  lines.push('}')
  return `${lines.join('\n')}\n`
}
